package com.nutricheck.backend.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

/**
 * Data Transfer Object (DTO) for report information.
 * This class is used to transfer report data over the REST API.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ReportDTO {
    // id should not be read when receiving a report as it is generated by the db
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String id;
    private String description;
    @NotBlank(message = "Recipe ID for a Report cannot be blank")
    private String recipeId;
    /*
     * these two fields are only used during deserialization as they allow the admin to quickly
     * assess the recipe details without needing to fetch it separately
     */
    private String recipeName;
    private String recipeInstructions;
}
