package com.nutricheck.backend.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;

import java.util.Objects;

/**
 * Data Transfer Object (DTO) for report information.
 * This class is used to transfer report data over the REST API.
 */
public class ReportDto {
    // id should not be read when receiving a report as it is generated by the db
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private String id;
    private String description;
    @NotBlank(message = "Recipe ID for a Report cannot be blank")
    private String recipeId;
    /*
     * these two fields are only used during deserialization as they allow the admin to quickly
     * assess the recipe details without needing to fetch it separately
     */
    private String recipeName;
    private String recipeInstructions;

    public ReportDto() {
    }

    public ReportDto(String id, String description, String recipeId, String recipeName, String recipeInstructions) {
        this.id = id;
        this.description = description;
        this.recipeId = recipeId;
        this.recipeName = recipeName;
        this.recipeInstructions = recipeInstructions;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(String recipeId) {
        this.recipeId = recipeId;
    }

    public String getRecipeName() {
        return recipeName;
    }

    public void setRecipeName(String recipeName) {
        this.recipeName = recipeName;
    }

    public String getRecipeInstructions() {
        return recipeInstructions;
    }

    public void setRecipeInstructions(String recipeInstructions) {
        this.recipeInstructions = recipeInstructions;
    }

    @Override
    public String toString() {
        return "ReportDto{" +
                "id='" + id + '\'' +
                ", description='" + description + '\'' +
                ", recipeId='" + recipeId + '\'' +
                ", recipeName='" + recipeName + '\'' +
                ", recipeInstructions='" + recipeInstructions + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ReportDto reportDto = (ReportDto) o;
        return Objects.equals(id, reportDto.id) &&
                Objects.equals(description, reportDto.description) &&
                Objects.equals(recipeId, reportDto.recipeId) &&
                Objects.equals(recipeName, reportDto.recipeName) &&
                Objects.equals(recipeInstructions, reportDto.recipeInstructions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, description, recipeId, recipeName, recipeInstructions);
    }
}
