package com.nutricheck.backend.layer.service.mapper;

import com.nutricheck.backend.dto.ReportDto;
import com.nutricheck.backend.layer.model.entity.Report;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * Mapper interface for converting between Report entities and ReportDTOs.
 * Utilizes MapStruct for automatic mapping generation.
 */
@Mapper(componentModel = "spring", unmappedTargetPolicy = org.mapstruct.ReportingPolicy.IGNORE)
public interface ReportMapper {
    ReportDto toDTO(Report report);
    @Mapping(target = "id", ignore = true) // ID will be generated by the database
    Report toEntity(ReportDto reportDTO);
    List<ReportDto> toDTO(List<Report> reports);
    List<Report> toEntity(List<ReportDto> reportDtos);
}
