package com.nutricheck.backend.integration;

import com.nutricheck.backend.TestDataFactory;
import com.nutricheck.backend.dto.RecipeDto;
import com.nutricheck.backend.dto.ReportDto;
import com.nutricheck.backend.layer.model.entity.Recipe;
import com.nutricheck.backend.layer.model.entity.Report;
import com.nutricheck.backend.layer.model.repository.RecipeRepository;
import com.nutricheck.backend.layer.model.repository.ReportRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.context.annotation.Import;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@Import(IntegrationTestConfig.class)
@ActiveProfiles("test")
class AdminIT {
    @Value("${spring.security.user.name}")
    private String username;
    @Value("${spring.security.user.password}")
    private String password;
    @Autowired
    private TestRestTemplate restTemplate;
    @Autowired
    private ReportRepository reportRepo;
    @Autowired
    private RecipeRepository recipeRepo;
    private Report report;
    private Recipe recipe;

    @BeforeEach
    void setup() {
        report = TestDataFactory.createDefaultReport();
        recipe = TestDataFactory.createDefaultRecipe();
    }
    @AfterEach
    void tearDown() {
        reportRepo.deleteAll();
        recipeRepo.deleteAll();
    }

    @Test
    void getAllReportsWithoutAuthTest() {
        ResponseEntity<List<ReportDto>> response = restTemplate.exchange(
                "/admin/reports",
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<List<ReportDto>>() {}
        );
        assertEquals(HttpStatus.UNAUTHORIZED, response.getStatusCode());
    }

    @Test
    void getAllReportsWithoutReportTest() {
        ResponseEntity<List<ReportDto>> response = restTemplate
                .withBasicAuth(username, password)
                .exchange(
                "/admin/reports",
                HttpMethod.GET,
                null,
                new ParameterizedTypeReference<List<ReportDto>>() {}
        );
        assertEquals(HttpStatus.OK, response.getStatusCode());
        List<ReportDto> reports = response.getBody();
        assertEquals(0, reports.size());
    }

    @Test
    void getAllReportsWithExistingOneTest() {
        reportRepo.saveAndFlush(report);

        ResponseEntity<List<ReportDto>> response = restTemplate
                .withBasicAuth(username, password)
                .exchange(
                        "/admin/reports",
                        HttpMethod.GET,
                        null,
                        new ParameterizedTypeReference<List<ReportDto>>() {}
                );
        assertEquals(HttpStatus.OK, response.getStatusCode());
        ReportDto expected = TestDataFactory.createDefaultReportDTO();
        assertEquals(1, response.getBody().size());
        ReportDto returned = response.getBody().get(0);
        // we cannot check for id because it is generated by the db
        assertEquals(expected.getDescription(), returned.getDescription());
        assertEquals(expected.getRecipeId(), returned.getRecipeId());
    }

    @Test
    void deleteReportTest() {
        Report managed = reportRepo.save(report);
        ResponseEntity<ReportDto> response = restTemplate
                .withBasicAuth(username, password)
                .exchange(
                        "/admin/reports/{reportId}",
                        HttpMethod.DELETE,
                        null,
                        ReportDto.class,
                        managed.getId()
                );
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals(0, reportRepo.findAll().size());
    }

    @Test
    void deleteRecipeTest() {
        recipeRepo.save(recipe);
        ResponseEntity<RecipeDto> response = restTemplate
                .withBasicAuth(username, password)
                .exchange(
                        "/admin/recipes/{recipeId}",
                        HttpMethod.DELETE,
                        null,
                        RecipeDto.class,
                        recipe.getId()
                );
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals(0, recipeRepo.findAll().size());
    }
}
