name: continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Mysql
        run: |
          sudo /etc/init.d/mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS nutri_check;" -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven
      - name: Configure Maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: |
            [{
              "id": "github",
              "username": "${{ github.actor }}",
              "password": "${{ secrets.GH_PAT }}"
            }]
      - name: Ensure test resources
        run: cp .github/workflows/application-test.properties src/test/resources/application-test.properties
      - name: Build with Maven
        run: mvn -B package --file pom.xml

